//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzerothWarsMapCompiler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WC3Optimizer\\VXJWTSOPT.exe")]
        public string Warcraft3OptimizerPath {
            get {
                return ((string)(this["Warcraft3OptimizerPath"]));
            }
            set {
                this["Warcraft3OptimizerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JassHelper\\jasshelper.exe")]
        public string JASSHelperPath {
            get {
                return ((string)(this["JASSHelperPath"]));
            }
            set {
                this["JASSHelperPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MpqEditor\\MpqEditor.exe")]
        public string MPQMasterPath {
            get {
                return ((string)(this["MPQMasterPath"]));
            }
            set {
                this["MPQMasterPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("common.j")]
        public string commonjPath {
            get {
                return ((string)(this["commonjPath"]));
            }
            set {
                this["commonjPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blizzard.j")]
        public string blizzardjPath {
            get {
                return ((string)(this["blizzardjPath"]));
            }
            set {
                this["blizzardjPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\compiledMaps\\")]
        public string CompiledMapsPath {
            get {
                return ((string)(this["CompiledMapsPath"]));
            }
            set {
                this["CompiledMapsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temp\\")]
        public string TemporaryFilePath {
            get {
                return ((string)(this["TemporaryFilePath"]));
            }
            set {
                this["TemporaryFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Warcraft III\\_retail_\\x86_64\\Warcraft III.exe")]
        public string Warcraft3FilePath {
            get {
                return ((string)(this["Warcraft3FilePath"]));
            }
            set {
                this["Warcraft3FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("w3x2lni_enUS_v2.7.2\\w2l.exe")]
        public string w3x2IniFilePath {
            get {
                return ((string)(this["w3x2IniFilePath"]));
            }
            set {
                this["w3x2IniFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mapCompilationPackages.json")]
        public string MapCompilationPackagesPath {
            get {
                return ((string)(this["MapCompilationPackagesPath"]));
            }
            set {
                this["MapCompilationPackagesPath"] = value;
            }
        }
    }
}
